version: '3.8'

services:
  db:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: musicnet_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: ["./wait-for-mysql.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
