# Generated by Django 5.2 on 2025-04-28 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
